In [1]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

# hyperbolic tan  and Sigmoid 

In [2]:
# tanh(x) - [-1,1] range of output  _____ it is rescaled logistic sigmoid function
# sigmoid - [0,1] range of output 

In [3]:
# calling the tanh(x) 
A = tf.nn.tanh([4,5,100,10000,10e-7])
print(sess.run(A))

[9.9932921e-01 9.9990916e-01 1.0000000e+00 1.0000000e+00 9.9999988e-07]


In [4]:
# calling sigmoid(x) 
B = tf.nn.sigmoid([4,5,100,10000,10e-7])

print(sess.run(B))

[0.98201376 0.9933071  1.         1.         0.50000024]


In [5]:
# calling relu(x)
C = tf.nn.relu([4,5,100,10000,10e-7])

print(sess.run(C))

[4.e+00 5.e+00 1.e+02 1.e+04 1.e-06]


In [6]:
# relu6
# softsign
# softplus
# elu 

# loss functions 

In [7]:
# for regression/numeric prediction, L1 or L2 can be the useful loss function.
# For classification, cross entropy can be the useful loss function. 
# Softmax or sigmoid cross entropy can be quite popular loss functions

In [9]:
pred = np.asarray([0.3,0.2,0.5])

# convert array to tensor 
x_val = tf.convert_to_tensor(pred)

# actual values 
actual = np.asarray([0.2,0.4,0.6])

In [10]:
#L2 loss: L2 = (pred-actual)^2 
l2 = tf.square(pred-actual)
l2_output = sess.run(tf.round(l2))

print(l2_output)

[0. 0. 0.]


In [11]:
# L1 loss: L1 = abs(pred-actual)
l1 = tf.abs(pred-actual)
l1_output = sess.run(tf.round(l1))

print(l1_output)

[0. 0. 0.]


# some common loss fucntions 
tf.contrib.losses.absolute_difference


tf.contrib.losses.add_loss
tf.contrib.losses.hinge_loss
tf.contrib.losses.compute_weighted_loss
tf.contrib.losses.cosine_distance
tf.contrib.losses.get_losses
tf.contrib.losses.get_regularization_losses
tf.contrib.losses.get_total_loss
tf.contrib.losses.log_loss
tf.contrib.losses.mean_pairwise_squared_error
tf.contrib.losses.mean_squared_error
tf.contrib.losses.sigmoid_cross_entropy
tf.contrib.losses.softmax_cross_entropy
tf.contrib.losses.sparse_softmax_cross_entropy
tf.contrib.losses.log(predictions,labels,weight=2.0)

# optimizers  
Initially you assume the initial values of weight and bias for the model (linear regression, etc.). Now you need to find the way to reach to the
best value of the parameters. The optimizer is the way to reach the best value of the parameters