In [1]:
import tensorflow as tf
sess = tf.Session()

C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\baban\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [3]:
# Creating a new graph 
myGraph = tf.Graph()

with myGraph.as_default():
    variable = tf.Variable(30, name = 'Baban')
    initialize = tf.global_variables_initializer()

In [4]:
with tf.Session(graph = myGraph) as sess:
    sess.run(initialize)
    print(sess.run(variable))

30


In [5]:
# creating a constant 
x = tf.constant(32,dtype ='float32')
print(tf.Session().run(x))

32.0


In [9]:
# working with constants and variables 
x = tf.constant(32,dtype ='float32')
y = tf.Variable(x+11) 
initialize = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(initialize)
    print(sess.run(y))

# also with a list of constants 
# working with constants and variables 
x = tf.constant([32,45,67,78])
y = tf.Variable(x+11) 
initialize = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(initialize)
    print(sess.run(y))

43.0
[43 56 78 89]


In [12]:
# place holders - they can be used later in the program____ generally used when storing n-D array 
x = tf.placeholder("float",None)  # None indicates that any number of rows are allowed 
y = x*10 +500 

with tf.Session() as sess:
    placeX = sess.run(y, feed_dict = {x:[0,5,8,89]})
    print(placeX)
    
# with 2D array 
with tf.Session() as sess:
    dataX = [[12,3,5,6],[4,5,6,7]]
    placeX = sess.run(y,feed_dict = {x:dataX}) # working with elementwise operations 
    print(placeX)

[ 500.  550.  580. 1390.]
[[620. 530. 550. 560.]
 [540. 550. 560. 570.]]


# Creating tensors 

In [22]:
# Fixed tensors - 

sess = tf.Session()

A = tf.ones([4,3])
print("ones\n",sess.run(A))

B = tf.zeros([3,3])
print("zeros\n", sess.run(B))

# fills with uniques number 
C = tf.fill([3,4], 13)
print("number fill\n",sess.run(C))

# creating tensor with diagoanl elements 
D = tf.diag([4,-3,6])
print("diagonal\n",sess.run(D))

ones
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
number fill
 [[13 13 13 13]
 [13 13 13 13]
 [13 13 13 13]]
diagonal
 [[ 4  0  0]
 [ 0 -3  0]
 [ 0  0  6]]


In [31]:
# sequence tensors 
# incremental with specified start, end, differnece values 
E = tf.range(start = 6, limit=10, delta = 0.9)
print("range method\n",sess.run(E),"\n")

# linspace - for evenly spaced 
F = tf.linspace(13.0,90.0,5) # the delta here needs to be int type 
print("evenly spaced\n",sess.run(F),"\n")

range method
 [6.       6.9      7.8      8.7      9.599999] 

evenly spaced
 [13.   32.25 51.5  70.75 90.  ] 



In [36]:
# Random tensors 

# generate random numbers within a range  from uniform distribution

G = tf.random_uniform([2,3],minval = -1, maxval =1)
print("from uniform distribution\n", sess.run(G),"\n")

# from normal distribution
H = tf.random_normal([2,3],mean=0, stddev=4)
print("From normal distribution\n",sess.run(H),"\n")

# also can be shuffled through another tensor 
I = tf.random_shuffle(tf.diag([3,6,-100]))
print("shuffled\n",sess.run(I),"\n")

from uniform distribution
 [[-0.21374774  0.6403055  -0.10344696]
 [ 0.03500223 -0.28473377 -0.86573577]] 

From normal distribution
 [[-1.6559175   0.70199275  8.595743  ]
 [ 1.9223752  -2.678854    1.0375268 ]] 

shuffled
 [[   3    0    0]
 [   0    6    0]
 [   0    0 -100]] 



# matrices 

In [48]:
A = tf.random_uniform([3,4])
B = tf.fill([4,2],1.2)
C = tf.random_normal([3,2])

sess.run(A)
sess.run(B)
sess.run(C)

array([[2.6014998 , 0.66639537],
       [0.2895544 , 0.1995347 ],
       [1.6692675 , 0.05700846]], dtype=float32)

In [50]:
print(sess.run(tf.matmul(A,B)),"\n") # MATrix MULtiplication

print(sess.run(tf.matmul(A,B)+C)) # multiplication and addition - beware of the dimensions

[[1.3318793 1.3318793]
 [3.161146  3.161146 ]
 [1.9671946 1.9671946]] 

[[1.8321986 3.0909147]
 [1.2206767 3.0197487]
 [3.683464  0.3124746]]
